# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Hotdogee.ToggleAudio
PackageVersion: 0.1.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- toggle-audio
- toggle-audiow
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hotdogee/toggle-audio/releases/download/v0.1.0/toggle-audio-0.1.0-x64.msi
  InstallerSha256: 474B295A402DC412508BF5E21F77D975A32EE38C0525C096856D870EB2EB4316
  ProductCode: '{9F03B824-00E3-45F7-9B6C-17BF741FE81D}'
  AppsAndFeaturesEntries:
  - DisplayName: Toggle Audio
    Publisher: Han Lin
    DisplayVersion: 0.1.0
    ProductCode: '{9F03B824-00E3-45F7-9B6C-17BF741FE81D}'
    UpgradeCode: '{C82A4013-F2FF-448E-A4AE-63CD73760A63}'
    InstallerType: wix
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-04
